
---

---
# Manipulação de dataframe - TAREFA 2 - Parte III
---

---

##1-) Leitura dos dados

A base de dados [Churn_Modelling](https://github.com/malegopc/DSBD/blob/main/Datasets/Churn/Churn_Modelling.csv) é utilizada para prever (classificar) quando um cliente irá parar de utilizar o serviço de um banco.

Conjunto de dados (características):

* Número de Instâncias: 10.000

* Número de Atributos: 13 atributos (incluindo o target)

* Informações dos Atributos:

  1. RowNumber
  2. CustomerId
  3. Surname
  4. CreditScore
  5. Geography
  6. Gender Age
  7. Tenure
  8. Balance
  9. NumOfProducts
  10. HasCrCard
  11. IsActiveMember
  12. EstimatedSalary
  13. Exited (variável de destino - target)

*Clone o repositório de dados da disciplina (https://github.com/malegopc/DSBD), faça a leitura do arquivo **Churn_Modelling.csv** disponível na pasta [Churn_Modelling](https://github.com/malegopc/DSBD/blob/main/Datasets/Churn) e armazene-o numa variável do tipo dataframe. Basta utilizar a função [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) da biblioteca pandas.*

In [47]:
!git clone https://github.com/malegopc/DSBD

Cloning into 'DSBD'...
remote: Enumerating objects: 770, done.
remote: Counting objects: 100% (313/313), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 770 (delta 166), reused 218 (delta 111), pack-reused 457 (from 1)
Receiving objects: 100% (770/770), 15.20 MiB | 9.27 MiB/s, done.
Resolving deltas: 100% (374/374), done.

In [48]:
!ls

Churn_Modelling_2.csv  Churn_Modelling.csv  DSBD

In [49]:
%cd Churn

[Errno 2] No such file or directory: 'Churn'
/content/DSBD/Datasets/Churn

In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("Churn_Modelling.csv")

clonado, e colocado na pasta correta usando %cd

##2-) Visualização do dataframe

*Mostre as 5 primeiras e as 5 últimas linhas do dataframe.*

In [52]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [53]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [54]:
df.tail(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

o "df" em si mostra as 5 primeiras e as 5 últimas, porém coloquei separado mesmo assim, usando "head" e "tail"

##3-) Eliminação manual de variáveis

*Elimine as variáveis (colunas): 'RowNumber', 'CustomerId' e 'Surname'.*

In [55]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

dropzinho based

##4-) Dados ausentes

*Verifique se há dados ausentes no dataframe.*

In [56]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

verificou se tem itens vazios... sendo 0 = false 1 = true, se nota que todas estão preenchidas...

## 5-) Separa as variáveis

*Utilizando a função **[iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html?highlight=iloc#pandas.DataFrame.iloc)**, copie para uma variável "X" os valores de todas as variáveis (colunas) do dataframe, exceto os valores da variável "Exited".*

*E copie para uma variável "y" somente os valores da variável "Exited".*

In [65]:
x = df.iloc[:, :-1]
y = df.iloc[:, :-1]

lê tds as linhas e colunas mas tira a ultima com -1, já que como visto acima "exited" é a ultima linha

In [66]:
print(x.head(5))



print(y.head(5))

   CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1
1          608     Spain  Female   41       1   83807.86              1
2          502    France  Female   42       8  159660.80              3
3          699    France  Female   39       1       0.00              2
4          850     Spain  Female   43       2  125510.82              1

   HasCrCard  IsActiveMember  EstimatedSalary
0          1               1        101348.88
1          0               1        112542.58
2          1               0        113931.57
3          0               0         93826.63
4          1               1         79084.10
   CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1
1          608     Spain  Female   41       1   83807.86              1
2          502    France  Female   42       8  159660.80              3
3          699    France  Female   39       1       0.00              2
4          850     Spain  Female   43       2  125510.82              1

   HasCrCard  IsActiveMember  EstimatedSalary
0          1               1        101348.88
1          0               1        112542.58
2          1               0        113931.57
3          0               0         93826.63
4          1               1         79084.10

AGORA SIM, X = Y copiado!